### ISSUE TITLE
Default user has not enough permissions

### ISSUE THREAD

**Issue by bobvandevijver** [lukasjapan/bt-speaker#17]
When the default btspeaker user is used on the latest Raspbian (Stretch), the user does not have enough permissions on the DBUS. Running the script as root works perfect.

```
$ python bt_speaker.py
ERROR:dbus.proxies:Introspect error on :1.4:/org/bluez/hci0: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.24" (uid=1001 pid=698 comm="python bt_speaker.py ") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.4" (uid=0 pid=469 comm="/usr/lib/bluetooth/bluetoothd ")
ERROR:dbus.connection:Unable to set arguments ('/endpoint/a2dpsink', dbus.Dictionary({u'Codec': dbus.Byte(0), u'UUID': dbus.String(u'0000110B-0000-1000-8000-00805F9B34FB'), u'DelayReporting': dbus.Boolean(True), u'Capabilities': dbus.Array([dbus.Byte(255), dbus.Byte(255), dbus.Byte(2), dbus.Byte(64)], signature=None)}, signature=None)) according to signature None: <type 'exceptions.TypeError'>: an integer is required
an integer is required
aplay: playback:2787: read error
```

**Comment by bobvandevijver** [comment]
This is fixed by adding the `btspeaker` user to the `bluetooth` group, and adding the `<allow send_type="method_call"></allow>` rule to the `bluetooth` group in `/etc/dbus-1/system.d/bluetooth.conf`.

**Comment by lukasjapan** [comment]
Oh, ok. Sounds like some policy changes in Raspbian...

Will check into this on the weekend and adjust the install script.

**Comment by bobvandevijver** [comment]
Not sure if it is a change, I've seen this specific error before (but is doesn't really matter). 

By the way, make sure to reload the dbus (`sudo systemctl reload dbus`) to make it work without reboot.

**Comment by lukasjapan** [comment]
Adding the `btspeaker` user to the `bluetooth` has been enough to make it work with the default raspbian image.

Install script was fixed.
