### ISSUE TITLE
iPhone AVRCP Volume Control

### ISSUE THREAD

**Issue by Julius112** [lukasjapan/bt-speaker#5]
Hello, first off all: Congratulations, great work! I haven't seen any other implementation of A2DP that needs nearly no configuration. The only problem, I currently have is that I can't control the ALSA volume on the iPhone. I tested it with an iPhone SE (iOS 10.3.1) and iPhone touch 4G (iOS 6.X). However, it works perfectly fine on an Android phone. So I assume the configuration is correct. Do you have any idea, what the problem is?

**Comment by Julius112** [comment]
Probably interesting to add: the script outputs volume change with the right values in percent, when I control the volume on iOS. However, on Android, it doesn't output anything, but the volume gets controlled correctly.

**Comment by lukasjapan** [comment]
I just checked it with the following setup:

- iPhone6 running iOS 10.3.1
- RaspberryPi 3
- raspbian 2017-04-10

I didn't have any problem with volume control (but had to fix another bug).

If the volume change output is showing, bt-speaker definitely got the signals over the AVRCP protocol.

It kind of sounds like some other software is interfering (pulseaudio?), maybe you could try to run bt-speaker on a fresh installation of raspbian and see how that goes.

**Comment by Julius112** [comment]
I tested it again on a fresh raspbian 2017-04-10 installation. It works perfectly fine with the onboard soundcard. However, when I use the USB Soundcard, I get the same strange situation:

- iOS: no volume control (except mute, when moving the slider to 0), volume change output is showing
- Android: volume control works, but no volume change output is showing

Could that have something to do with a wrong calculation/range for the volume level?

**Comment by lukasjapan** [comment]
I see, I haven't tried the setup with an external soundcard yet (I don't have one) but I think the following is happening:

iOS:
- bt-speaker controls the volume of the on board sound not of the USB soundcard
- aplay sends the sound to your USB soundcard as desired
- iOS sends an empty sound signal on mute (0% volume)

Android:
- I believe some other mechanism I do not know about takes over control. Well, as long as it works...

So, to make volume control work with the USB soundcard you probably need to adjust [the alsa mixer initialization code](https://github.com/lukasjapan/bt-speaker/blob/master/bt_speaker.py#L51).

[Documentation of alsaaudio.Mixer](https://larsimmisch.github.io/pyalsaaudio/libalsaaudio.html#mixer-objects)

I suspect that you need to add `cardindex=1` but it could also be a different argument set.
Please try to find out what will work for you.

Bt-speaker also has a config file (`/etc/bt_speaker/config.ini`) but only the `control` argument of alsa mixer can be set by that at the moment.
I think I should make the other arguments configurable too.

**Comment by Julius112** [comment]
That fixed the problem! I had to change the mixer name in the config.ini as well but then it worked perfectly fine. However, I can't test it with an Andriod phone right now.

I left the issue open as you said you want to make some changes. If you would like me to write a patch, then I'm happy to do so :)

Danke für die Hilfe und viele Grüße nach Deutschland!

**Comment by Julius112** [comment]
I've created a patch for that problem. Feel free to apply it to the repository.

[PATCH_ISSUE5.txt](https://github.com/lukasjapan/bt-speaker/files/981149/PATCH_ISSUE5.txt)

Cheers,
Julius

**Comment by lukasjapan** [comment]
Thanks!

I'll add some documentation and merge it via a pull request in the next days.

Cheers

**Comment by lukasjapan** [comment]
Done.
I also added the `id` parameter and did a little refactoring.
