### ISSUE TITLE
Display track metadata

### ISSUE THREAD

**Issue by wesaou** [lukasjapan/bt-speaker#65]
Firstly, that you for this project. It has made bluetooth pairing so simplistic it's unreal compare to the hoops that I had to jump through previously. But, I was wondering how hard/simple it would be to snag track metadata. Whether that could be through a script to interact with BlueZ or something of the sort, I would love to be pointed in the right direction! Thanks!

**Comment by pktmterenceg** [comment]
Using some of the examples at https://scribles.net/controlling-bluetooth-audio-on-raspberry-pi/ I was able to get track information displayed. I was further able to get album art via https://github.com/desbma/sacad. Hope this helps!

**Comment by lukasjapan** [comment]
Now in master
